//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoadHelp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string F_Relation { get; set; }
        public Nullable<int> Member_id { get; set; }
    }
}
