//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoadHelp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnRoadHelpEntities1 : DbContext
    {
        public OnRoadHelpEntities1()
            : base("name=OnRoadHelpEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<HelpRequest> HelpRequests { get; set; }
        public virtual DbSet<HelpRequestAssigned> HelpRequestAssigneds { get; set; }
        public virtual DbSet<AvailableService> AvailableServices { get; set; }
        public virtual DbSet<AddService> AddServices { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
